// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pierskarsenbarg/provider-base/sdk/go/base/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

var _ = internal.GetEnvOrDefault

// Your access token
func GetAccessToken(ctx *pulumi.Context) string {
	return config.Get(ctx, "base:accessToken")
}

// Environment
func GetEnvironment(ctx *pulumi.Context) string {
	return config.Get(ctx, "base:environment")
}
