# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .account import *
from .get_account import *
from .provider import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pierskarsenbarg_pulumi_base.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pierskarsenbarg_pulumi_base.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "base",
  "mod": "index",
  "fqn": "pierskarsenbarg_pulumi_base",
  "classes": {
   "base:index:Account": "Account"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "base",
  "token": "pulumi:providers:base",
  "fqn": "pierskarsenbarg_pulumi_base",
  "class": "Provider"
 }
]
"""
)
