// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package base

import (
	"context"
	"reflect"

	"github.com/pierskarsenbarg/provider-base/sdk/go/base/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumix"
)

// Account to define
type Account struct {
	pulumi.CustomResourceState

	// Id of account created
	AccountId pulumix.Output[string] `pulumi:"accountId"`
	// Environment of account
	Environment pulumix.Output[string] `pulumi:"environment"`
	// Name of account created
	Name pulumix.Output[string] `pulumi:"name"`
}

// NewAccount registers a new resource with the given unique name, arguments, and options.
func NewAccount(ctx *pulumi.Context,
	name string, args *AccountArgs, opts ...pulumi.ResourceOption) (*Account, error) {
	if args == nil {
		args = &AccountArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Account
	err := ctx.RegisterResource("base:index:Account", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetAccount gets an existing Account resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetAccount(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *AccountState, opts ...pulumi.ResourceOption) (*Account, error) {
	var resource Account
	err := ctx.ReadResource("base:index:Account", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Account resources.
type accountState struct {
}

type AccountState struct {
}

func (AccountState) ElementType() reflect.Type {
	return reflect.TypeOf((*accountState)(nil)).Elem()
}

type accountArgs struct {
	// Name of account
	Name *string `pulumi:"name"`
}

// The set of arguments for constructing a Account resource.
type AccountArgs struct {
	// Name of account
	Name pulumix.Input[*string]
}

func (AccountArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*accountArgs)(nil)).Elem()
}

type AccountOutput struct{ *pulumi.OutputState }

func (AccountOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*Account)(nil)).Elem()
}

func (o AccountOutput) ToAccountOutput() AccountOutput {
	return o
}

func (o AccountOutput) ToAccountOutputWithContext(ctx context.Context) AccountOutput {
	return o
}

func (o AccountOutput) ToOutput(ctx context.Context) pulumix.Output[Account] {
	return pulumix.Output[Account]{
		OutputState: o.OutputState,
	}
}

// Id of account created
func (o AccountOutput) AccountId() pulumix.Output[string] {
	value := pulumix.Apply[Account](o, func(v Account) pulumix.Output[string] { return v.AccountId })
	return pulumix.Flatten[string, pulumix.Output[string]](value)
}

// Environment of account
func (o AccountOutput) Environment() pulumix.Output[string] {
	value := pulumix.Apply[Account](o, func(v Account) pulumix.Output[string] { return v.Environment })
	return pulumix.Flatten[string, pulumix.Output[string]](value)
}

// Name of account created
func (o AccountOutput) Name() pulumix.Output[string] {
	value := pulumix.Apply[Account](o, func(v Account) pulumix.Output[string] { return v.Name })
	return pulumix.Flatten[string, pulumix.Output[string]](value)
}

func init() {
	pulumi.RegisterOutputType(AccountOutput{})
}
