name: pr
on:
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  build_sdks:
    name: Build SDKs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5
      - name: Unshallow clone for tags
        run: git fetch --prune --unshallow --tags
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.26.x"
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: "24.x"
      - name: Setup DotNet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "10.0.201"
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"
      - name: Install Pulumi CLI
        uses: pulumi/actions@v7
      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install pulumictl
        uses: jaxxstorm/action-install-gh-release@v2.1.0
        with:
          repo: pulumi/pulumictl
      - name: build sdk
        run: task build_sdks