// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * GetOrganization gets the Organization information
 */
export function getAccount(args: GetAccountArgs, opts?: pulumi.InvokeOptions): Promise<GetAccountResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("base:index:getAccount", {
        "accountName": args.accountName,
    }, opts);
}

export interface GetAccountArgs {
    /**
     * Name of the Account
     */
    accountName: string;
}

export interface GetAccountResult {
    /**
     * Id of account created
     */
    readonly accountId: string;
    /**
     * Environment of account
     */
    readonly environment: string;
    /**
     * Name of account created
     */
    readonly name: string;
}
/**
 * GetOrganization gets the Organization information
 */
export function getAccountOutput(args: GetAccountOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetAccountResult> {
    return pulumi.output(args).apply((a: any) => getAccount(a, opts))
}

export interface GetAccountOutputArgs {
    /**
     * Name of the Account
     */
    accountName: pulumi.Input<string>;
}
